### ISSUE TITLE
Requirements class links and dependencies?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#112]
I'm noting that a lot of the abstract tests link to OGC API Common Core as their dependency but the document link goes to EDR core. 

There's also not a real clear set of requirements class links between our abstract test conformance classes and requirements classes -- maybe I'm just missing it, but we need to spend some time getting all these links straight.

Files from this commit: https://github.com/opengeospatial/Environmental-Data-Retrieval-API/pull/109/commits/6feeef9b09d40297d2ea2e449448a20b85c0daee touch on a few of those issues.

**Comment by dblodgett-usgs** [comment]
Some of these are due to requirements classes not being imported -- e.g. the html requirements class is a recommendation but still linked as if it's a requirement.

**Comment by m-burgoyne** [comment]
We should prioritise tests for requirements, but I think it is worth providing as much information as possible to help producers and consumers of the API for anything that is defined by the specification.

**Comment by dblodgett-usgs** [comment]
Right. To be more specific, here: http://docs.opengeospatial.org/DRAFTS/19-086.html#_encodings 

encodings are recommendations. 

Bet here: http://docs.opengeospatial.org/DRAFTS/19-086.html#_conformance_class_html

They are referred to as requirements. 

Should we convert the recommendations to optional requirements or link to the recommendations in the tests?

**Comment by chris-little** [comment]
@dblodgett-usgs @m-burgoyne "Requirements/Recommendations/Permissions" are standard terminology. I think we should link to the recommendations in the tests. A test suite that tells us "This implementation meets the requirements, and also meets these, extra, recommendations" is a much better test suite.

**Comment by dblodgett-usgs** [comment]
Decision to just link to recommendations and move on. Still need to implement those changes where applicable.

**Comment by dblodgett-usgs** [comment]
Second question on this issue. The abstract tests for core and collections link to `http://www.opengis.net/spec/ogcapi_common/1.0/req/core`. Dhould the requirements class links for each test link directly to Common with whatever extended path is needed? Most of those links are broken because they go to non-existent requirements in EDR.

e.g. 
![Screen Shot 2020-08-12 at 8 53 10 PM](https://user-images.githubusercontent.com/1492803/90085550-dd7c1080-dcdd-11ea-9cff-1ace828c9e0f.png)

Should `/req/collections/rc-md-op` link to `http://www.opengis.net/spec/ogcapi_common/1.0/req/core/req/collections/rc-md-op`?

**Comment by chris-little** [comment]
@dblodgett-usgs @m-burgoyne @ghobona @cmheazel We originally decided to have a 'self-contained' document, so that users and web developers didn't have to go to several documents. That is why we lifted complete sections of OGC API Features and then Common text. 
I think there nows needs to be a clear cross-API agreement on how to handle shared tests, namespaces and URIs.
I would prefer that we copy the appropriate text for the tests and requirements from API Common Core and Collections, but use the Commmon URIs for them.

**Comment by dblodgett-usgs** [comment]
We need to open a new issue that is pending availability of links in API Common.

**Comment by cmheazel** [comment]
@chris-little It's also possible to include files across GitHub repositories.  So rather than copy content, you just have to include it.
We will have to break the files in Common into smaller chunks.  But if there is a need it can be done.

**Comment by chris-little** [comment]
@cmheazel Understood, but when we started this journey two years ago, not all repos were in the OGC space; it was not clear what document styles we were going to use, and EDR API decided to take a snapshot of OGC API-Common (as it is now known) so that the EDR document would be self-contained and be, to some extent, insulated from moving goal-posts.
Moving towards self-contained 'atomic' chunks of text is to be welcomed.
