### ISSUE TITLE
Is use of CoverageJSON a risk to interoperability with OGC API - Coverages?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/Environmental-Data-Retrieval-API#117]
The [Conformance section](http://docs.opengeospatial.org/DRAFTS/19-086.html#_conformance) of the EDR API states that:

"Neither the Core nor Collection requirements classes mandate specific encodings or formats for representing resources. The HTML, GeoJSON and CoverageJSON requirements classes specify representations for these resources in frequently used encodings for spatial data on the web.

None of these encodings are mandatory. An implementation of the EDR API may decide to implement another encoding instead of, or in addition to, those listed. However, a common format does simplify interoperability so support for CoverageJSON is highly recommended as an established, efficient and effective format."

Are there any risks to interoperability with OGC API - Coverages regarding the use of CoverageJSON?

If there are any risks, could those risks be mitigated somehow?

Please coordinate on this discussion with the OGC API - Coverages SWG.

**Comment by m-burgoyne** [comment]
With EDR it is up to the publisher of the collection which formats they will support and if interoperability with an OGC API - Coverages service was a key requirement for the collection CIS JSON could be offered as an output format.  

CoverageJSON was chosen because there are existing software libraries which make it possible to produce and consume the format and it has a well defined schema with the ability to describe the responses from the EDR query patterns.

**Comment by ghobona** [comment]
This issue appears to have been [resolved](https://github.com/opengeospatial/ogc_api_coverages/blob/f915e7c53502b65d1b4cb139f0e3907df4b7f573/standard/recommendations/geodata-coverage/REC_covjson.adoc).

OGC API - Coverages now allows for CoverageJSON too.

@jerstlouis Would you agree that this is no longer an issue?

**Comment by jerstlouis** [comment]
@ghobona I would say any variability is a potential cause for interoperability issue, but that has to be balanced with the desire to support different communities with different preferences. Personally, I do find it odd and confusing that there are two entirely different OGC standards to encode coverage data as JSON, rather than say extensions to support slightly different use cases.

Per the last update of OGC API - Coverages in the GitHub repository, there is no longer a "default" encoding for coverages.
However, a CIS JSON encoding of the DomainSet and RangeType is required to be either embedded in (as JSON properties) or linked from the `/collections/{collectionId}` resource. If using links, those resources could also additionally be available in additonal formats. A CIS JSON conformance class is defined and recommended to be implemented, i.e. offering the coverage as CIS JSON. An implementation is however free to offer the whole coverage as CoverageJSON only, or as GeoTIFF only, as long as the domain set and range type is available as CIS JSON from the `{collectionId}` resource.

CoverageJSON encoding should use a Coverage-JSON-specific media type (not `application/json`, which in _OGC API - Coverages_ is understood to mean CIS JSON).

**Comment by ghobona** [comment]
@jerstlouis I'm happy with the resolution.

...just to clarify though. CoverageJSON is not yet an OGC standard. Hopefully it will be submitted for standardisation in the future.

**Comment by ghobona** [comment]
@schpidi clarified today in the OGC API - Coverages Sprint that CoverageJSON is a current work item in the WCS SWG/Coverages SWG. 

The sprint also observed that CoverageJSON uses `application/prs.coverage+json`. This addresses the issue in paragraph 3 of Comment https://github.com/opengeospatial/Environmental-Data-Retrieval-API/issues/117#issuecomment-669743320.

This Issue has been resolved and can be closed.

**Comment by jerstlouis** [comment]
Also, we agreed to use `application/json` for CIS JSON for the purpose of the sprint, but remarked that clarifying it with e.g. a `; subtype=ogc.cis.json` or a dedicated media type might further help avoid confusion.
