### ISSUE TITLE
How to handle "statistic codes" in the context of EDR?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/Environmental-Data-Retrieval-API#145]
The USGS organizes it's observational data by both parameter and statistic. Our primary API allows one to request one or the other. This is especially true for daily-values where they are ostensibly always some kind of daily summary of instantaneous measurements.

The data model for these statistic codes is a little messy, but in essence a request has to include both the parameter of interest and the statistic of interest. 

It seems like conflating these two into parameter is the way we would handle this? 

Would it be worth considering this use case where we would map "parameter" onto Observed Property and introduce a new "procedure" or something similar to accommodate different summaries of that property?

Or am I missing something?

**Comment by dblodgett-usgs** [comment]
Think I'm going to answer my own question here. These fit quite nicely into the "measurementType" attribute of a given parameter. 

Is this how the group is interpreting measurementType?  

e.g. I might have:
```json
        "s00003_p00060": {
          "type": "Parameter",
          "description": {
            "en": "DAILY MEAN VALUES Streamflow, ft³/s",
            "sp": "todo"
          },
          "unit": {
            "label": {
              "en": "ft³/s",
              "sp": "todo"
            },
            "symbol": {
              "value": "units",
              "type": "https://todo"
            }
          },
          "observedProperty": {
            "id": "https://waterdata.usgs.gov/nwisweb/rdf?parmCd=00060",
            "label": {
              "en": "Streamflow, ft³/s",
              "sp": "todo"
            }
          },
          "measurementType": {
            "id": "https://waterdata.usgs.gov/nwisweb/rdf?statCd=00003",
            "method": "DAILY MEAN VALUES",
            "period": "P1D"
          }
        }
```

**Comment by m-burgoyne** [comment]
The way that I viewed the measurement type  definition was as follows:

  "method" : "MEAN"
  "period" : "P1D"

the the values in the data array are the Mean over the defined period, where the period was defined as from the date value in the time dimension to the date value + 1 Day

If the value was the Mean for the previous Day (up until the time value defined in the time dimension) 

  "method" : "MEAN"
  "period" : "-1D"

**Comment by chris-little** [comment]
@dblodgett-usgs , @m-burgoyne This may be slightly off-topic, but we tackled this problem, decades ago, when we invented GRIB and BUFR, and took a pragmatic approach. BUFR has a mechanism for declaring a statistic of a parameter by qualifying it.  But for those statistics that were pervasive and very common, such as wind speed and wind gust, they have their own parameter code (which implies the mean over 10 minutes, and max 3 second running mean over 10 mins). The same mechanism is used for other qualifying aspects such as Temperature (at standard 2m height above the ground, in a standard exposure screen, on a recently calibrated thermometer). The non-specific parameter codes have to have the full gamut of attributes/properties such as x,y,z,t, etc.
So, do we want the end user to know this? Probably not. 
Similarly, when we pre-calculate some statistics, rather than have them calculated on the fly when requested, do we give them a separate atomic parameter name that cannot be parsed? Again probably not.
This is good stuff for the next version of EDR API.

**Comment by tervo** [comment]
It would be nice if all this meta information could be given as a link to another resource. This would keep responses small and let them focus on the relevant part: data itself. How is it in the current spec?

**Comment by m-burgoyne** [comment]
@tervo The intention is that only the essential information required to describe and differentiate the parameters is included in the responses, that essential information will include links to the more detailed meta information where required.

**Comment by tervo** [comment]
In most requests, meta information like aggregation methods are NOT actually essential information even if they are not standard. In many cases, they are required once while the process employing the API is developed. In case of more intelligent clients, the meta information may be used while parsing each request but such clients are most probably capable to follow links as well.

**Comment by m-burgoyne** [comment]
I think it can be useful when labels are vague, the suggested approach is probably less verbose than a unique URI and still allows a client to identify how the data was aggregated.

**Comment by dblodgett-usgs** [comment]
OK - thanks @m-burgoyne - your comment above answers the basic question. I think we will be ok using method/period to describe the stat code and observedProperty to describe parameter code.
