### ISSUE TITLE
Polygon and tile edges as 'straight' lines

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/Environmental-Data-Retrieval-API#56]
This issue was left unresolved in the Sprint.
https://github.com/opengeospatial/EDR-API-Sprint/issues/5#issue-580244819 

Data to be retrieved from various data stores by specifying an Area as a polygon ( (x1,y1), (x2,y2),...(xn,yn), (x1,y1) )

1. Simple polygon with a few corners. DONE, but have we assumed the polygon is convex? 

2. Complex polygon with many corners, such as a country, state, town or county border. This could be a performance issue. Do we limit the number of polygon vertices? 

3. Special case of rectangle: do we allow a bounding box with only two corners specified? It maybe simpler for the user, but is a different pattern.

4. What is considered a straight line for the boundary edges of the polygon if data store uses a different CRS from WGS84? Straiaght in the CRS or great circle lines in WGS84?

**Comment by m-burgoyne** [comment]
@chris-little 

I do not think that suggestion 3 would work with WKT.  

I also think that most of these questions should not be decided by the EDR API but rather by the data provider.  I think that those questions should be decided at collection level (and advertised in the service metadata).  Otherwise we are creating technical overheads which will limit the technology choices of the data providers.

**Comment by chris-little** [comment]
@m-burgoyne Agreed. We do not allow a rectangle to be specified by diagonal corners - we go with WKT, if a user wants data over a rectangle, they create a Polygon query. with all four points specified.
